package com.jeremy.lychee.db2;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jeremy.lychee.db2.WeMediaChannel;
import com.jeremy.lychee.db2.WeMediaTopic;
import com.jeremy.lychee.db2.NewsChannel;
import com.jeremy.lychee.db2.NewsListData;
import com.jeremy.lychee.db2.ThumbsUp;
import com.jeremy.lychee.db2.Program;
import com.jeremy.lychee.db2.LiveColumnListData;
import com.jeremy.lychee.db2.LiveHotItem;

import com.jeremy.lychee.db2.WeMediaChannelDao;
import com.jeremy.lychee.db2.WeMediaTopicDao;
import com.jeremy.lychee.db2.NewsChannelDao;
import com.jeremy.lychee.db2.NewsListDataDao;
import com.jeremy.lychee.db2.ThumbsUpDao;
import com.jeremy.lychee.db2.ProgramDao;
import com.jeremy.lychee.db2.LiveColumnListDataDao;
import com.jeremy.lychee.db2.LiveHotItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weMediaChannelDaoConfig;
    private final DaoConfig weMediaTopicDaoConfig;
    private final DaoConfig newsChannelDaoConfig;
    private final DaoConfig newsListDataDaoConfig;
    private final DaoConfig thumbsUpDaoConfig;
    private final DaoConfig programDaoConfig;
    private final DaoConfig liveColumnListDataDaoConfig;
    private final DaoConfig liveHotItemDaoConfig;

    private final WeMediaChannelDao weMediaChannelDao;
    private final WeMediaTopicDao weMediaTopicDao;
    private final NewsChannelDao newsChannelDao;
    private final NewsListDataDao newsListDataDao;
    private final ThumbsUpDao thumbsUpDao;
    private final ProgramDao programDao;
    private final LiveColumnListDataDao liveColumnListDataDao;
    private final LiveHotItemDao liveHotItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weMediaChannelDaoConfig = daoConfigMap.get(WeMediaChannelDao.class).clone();
        weMediaChannelDaoConfig.initIdentityScope(type);

        weMediaTopicDaoConfig = daoConfigMap.get(WeMediaTopicDao.class).clone();
        weMediaTopicDaoConfig.initIdentityScope(type);

        newsChannelDaoConfig = daoConfigMap.get(NewsChannelDao.class).clone();
        newsChannelDaoConfig.initIdentityScope(type);

        newsListDataDaoConfig = daoConfigMap.get(NewsListDataDao.class).clone();
        newsListDataDaoConfig.initIdentityScope(type);

        thumbsUpDaoConfig = daoConfigMap.get(ThumbsUpDao.class).clone();
        thumbsUpDaoConfig.initIdentityScope(type);

        programDaoConfig = daoConfigMap.get(ProgramDao.class).clone();
        programDaoConfig.initIdentityScope(type);

        liveColumnListDataDaoConfig = daoConfigMap.get(LiveColumnListDataDao.class).clone();
        liveColumnListDataDaoConfig.initIdentityScope(type);

        liveHotItemDaoConfig = daoConfigMap.get(LiveHotItemDao.class).clone();
        liveHotItemDaoConfig.initIdentityScope(type);

        weMediaChannelDao = new WeMediaChannelDao(weMediaChannelDaoConfig, this);
        weMediaTopicDao = new WeMediaTopicDao(weMediaTopicDaoConfig, this);
        newsChannelDao = new NewsChannelDao(newsChannelDaoConfig, this);
        newsListDataDao = new NewsListDataDao(newsListDataDaoConfig, this);
        thumbsUpDao = new ThumbsUpDao(thumbsUpDaoConfig, this);
        programDao = new ProgramDao(programDaoConfig, this);
        liveColumnListDataDao = new LiveColumnListDataDao(liveColumnListDataDaoConfig, this);
        liveHotItemDao = new LiveHotItemDao(liveHotItemDaoConfig, this);

        registerDao(WeMediaChannel.class, weMediaChannelDao);
        registerDao(WeMediaTopic.class, weMediaTopicDao);
        registerDao(NewsChannel.class, newsChannelDao);
        registerDao(NewsListData.class, newsListDataDao);
        registerDao(ThumbsUp.class, thumbsUpDao);
        registerDao(Program.class, programDao);
        registerDao(LiveColumnListData.class, liveColumnListDataDao);
        registerDao(LiveHotItem.class, liveHotItemDao);
    }
    
    public void clear() {
        weMediaChannelDaoConfig.getIdentityScope().clear();
        weMediaTopicDaoConfig.getIdentityScope().clear();
        newsChannelDaoConfig.getIdentityScope().clear();
        newsListDataDaoConfig.getIdentityScope().clear();
        thumbsUpDaoConfig.getIdentityScope().clear();
        programDaoConfig.getIdentityScope().clear();
        liveColumnListDataDaoConfig.getIdentityScope().clear();
        liveHotItemDaoConfig.getIdentityScope().clear();
    }

    public WeMediaChannelDao getWeMediaChannelDao() {
        return weMediaChannelDao;
    }

    public WeMediaTopicDao getWeMediaTopicDao() {
        return weMediaTopicDao;
    }

    public NewsChannelDao getNewsChannelDao() {
        return newsChannelDao;
    }

    public NewsListDataDao getNewsListDataDao() {
        return newsListDataDao;
    }

    public ThumbsUpDao getThumbsUpDao() {
        return thumbsUpDao;
    }

    public ProgramDao getProgramDao() {
        return programDao;
    }

    public LiveColumnListDataDao getLiveColumnListDataDao() {
        return liveColumnListDataDao;
    }

    public LiveHotItemDao getLiveHotItemDao() {
        return liveHotItemDao;
    }

}
