package com.jeremy.lychee.db2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LIVE_HOT_ITEM.
 */
public class LiveHotItem {

    /** Not-null value. */
    private String id;
    private String video_channel_name;
    private String video_column_id;
    private String video_column_name;
    private String video_type;
    private String video_desc;
    private String video_name;
    private String video_duration;
    private String video_icon;
    private String video_publish_status;
    private String video_img;
    private String video_islive;
    private String video_play_url;
    private String video_url;
    private String pdate;
    private String tag;
    private String watches;
    private String is_seg;
    private String news_type;
    private String news_from;
    private String zm;
    private String video_key;
    private String comment;
    private String ding;
    private String share;
    private String is_focus;
    private Long time;
    private String source;

    public LiveHotItem() {
    }

    public LiveHotItem(String id) {
        this.id = id;
    }

    public LiveHotItem(String id, String video_channel_name, String video_column_id, String video_column_name, String video_type, String video_desc, String video_name, String video_duration, String video_icon, String video_publish_status, String video_img, String video_islive, String video_play_url, String video_url, String pdate, String tag, String watches, String is_seg, String news_type, String news_from, String zm, String video_key, String comment, String ding, String share, String is_focus, Long time, String source) {
        this.id = id;
        this.video_channel_name = video_channel_name;
        this.video_column_id = video_column_id;
        this.video_column_name = video_column_name;
        this.video_type = video_type;
        this.video_desc = video_desc;
        this.video_name = video_name;
        this.video_duration = video_duration;
        this.video_icon = video_icon;
        this.video_publish_status = video_publish_status;
        this.video_img = video_img;
        this.video_islive = video_islive;
        this.video_play_url = video_play_url;
        this.video_url = video_url;
        this.pdate = pdate;
        this.tag = tag;
        this.watches = watches;
        this.is_seg = is_seg;
        this.news_type = news_type;
        this.news_from = news_from;
        this.zm = zm;
        this.video_key = video_key;
        this.comment = comment;
        this.ding = ding;
        this.share = share;
        this.is_focus = is_focus;
        this.time = time;
        this.source = source;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getVideo_channel_name() {
        return video_channel_name;
    }

    public void setVideo_channel_name(String video_channel_name) {
        this.video_channel_name = video_channel_name;
    }

    public String getVideo_column_id() {
        return video_column_id;
    }

    public void setVideo_column_id(String video_column_id) {
        this.video_column_id = video_column_id;
    }

    public String getVideo_column_name() {
        return video_column_name;
    }

    public void setVideo_column_name(String video_column_name) {
        this.video_column_name = video_column_name;
    }

    public String getVideo_type() {
        return video_type;
    }

    public void setVideo_type(String video_type) {
        this.video_type = video_type;
    }

    public String getVideo_desc() {
        return video_desc;
    }

    public void setVideo_desc(String video_desc) {
        this.video_desc = video_desc;
    }

    public String getVideo_name() {
        return video_name;
    }

    public void setVideo_name(String video_name) {
        this.video_name = video_name;
    }

    public String getVideo_duration() {
        return video_duration;
    }

    public void setVideo_duration(String video_duration) {
        this.video_duration = video_duration;
    }

    public String getVideo_icon() {
        return video_icon;
    }

    public void setVideo_icon(String video_icon) {
        this.video_icon = video_icon;
    }

    public String getVideo_publish_status() {
        return video_publish_status;
    }

    public void setVideo_publish_status(String video_publish_status) {
        this.video_publish_status = video_publish_status;
    }

    public String getVideo_img() {
        return video_img;
    }

    public void setVideo_img(String video_img) {
        this.video_img = video_img;
    }

    public String getVideo_islive() {
        return video_islive;
    }

    public void setVideo_islive(String video_islive) {
        this.video_islive = video_islive;
    }

    public String getVideo_play_url() {
        return video_play_url;
    }

    public void setVideo_play_url(String video_play_url) {
        this.video_play_url = video_play_url;
    }

    public String getVideo_url() {
        return video_url;
    }

    public void setVideo_url(String video_url) {
        this.video_url = video_url;
    }

    public String getPdate() {
        return pdate;
    }

    public void setPdate(String pdate) {
        this.pdate = pdate;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getWatches() {
        return watches;
    }

    public void setWatches(String watches) {
        this.watches = watches;
    }

    public String getIs_seg() {
        return is_seg;
    }

    public void setIs_seg(String is_seg) {
        this.is_seg = is_seg;
    }

    public String getNews_type() {
        return news_type;
    }

    public void setNews_type(String news_type) {
        this.news_type = news_type;
    }

    public String getNews_from() {
        return news_from;
    }

    public void setNews_from(String news_from) {
        this.news_from = news_from;
    }

    public String getZm() {
        return zm;
    }

    public void setZm(String zm) {
        this.zm = zm;
    }

    public String getVideo_key() {
        return video_key;
    }

    public void setVideo_key(String video_key) {
        this.video_key = video_key;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getDing() {
        return ding;
    }

    public void setDing(String ding) {
        this.ding = ding;
    }

    public String getShare() {
        return share;
    }

    public void setShare(String share) {
        this.share = share;
    }

    public String getIs_focus() {
        return is_focus;
    }

    public void setIs_focus(String is_focus) {
        this.is_focus = is_focus;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

}
