package com.jeremy.lychee.db2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS_CHANNEL.
 */
public class NewsChannel {

    /** Not-null value. */
    private String cid;
    private String cname;
    private String icon;
    private String tagname;
    private String init;
    private String is_start;
    private Boolean isShow;

    public NewsChannel() {
    }

    public NewsChannel(String cid) {
        this.cid = cid;
    }

    public NewsChannel(String cid, String cname, String icon, String tagname, String init, String is_start, Boolean isShow) {
        this.cid = cid;
        this.cname = cname;
        this.icon = icon;
        this.tagname = tagname;
        this.init = init;
        this.is_start = is_start;
        this.isShow = isShow;
    }

    /** Not-null value. */
    public String getCid() {
        return cid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getCname() {
        return cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getTagname() {
        return tagname;
    }

    public void setTagname(String tagname) {
        this.tagname = tagname;
    }

    public String getInit() {
        return init;
    }

    public void setInit(String init) {
        this.init = init;
    }

    public String getIs_start() {
        return is_start;
    }

    public void setIs_start(String is_start) {
        this.is_start = is_start;
    }

    public Boolean getIsShow() {
        return isShow;
    }

    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

}
