package com.jeremy.lychee.db2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table THUMBS_UP.
 */
public class ThumbsUp {

    /** Not-null value. */
    private String id;
    private boolean voted;

    public ThumbsUp() {
    }

    public ThumbsUp(String id) {
        this.id = id;
    }

    public ThumbsUp(String id, boolean voted) {
        this.id = id;
        this.voted = voted;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public boolean getVoted() {
        return voted;
    }

    public void setVoted(boolean voted) {
        this.voted = voted;
    }

}
