package com.jeremy.lychee.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS_LIST_DATA.
 */
public class NewsListData {

    private Long _id;
    private String id;
    private String nid;
    private String uid;
    private String channel;
    private Long time;
    private String md5;
    private String cid;
    private String album_pic;
    private String title;
    private String zm;
    private String url;
    private String comment;
    private String pdate;
    private String source;
    private String module;
    private String share;
    private String news_from;
    private String open_type;
    private String news_type;
    private String news_data;
    private String news_stick;
    private String news_stick_time;
    private String transmit_num;
    private String is_focus;
    private String uuid_flag;
    private String video_length;
    private String live_channel_id;
    private String live_topic_id;
    private String live_channel_tag;
    private String summary;

    public NewsListData() {
    }

    public NewsListData(Long _id) {
        this._id = _id;
    }

    public NewsListData(Long _id, String id, String nid, String uid, String channel, Long time, String md5, String cid, String album_pic, String title, String zm, String url, String comment, String pdate, String source, String module, String share, String news_from, String open_type, String news_type, String news_data, String news_stick, String news_stick_time, String transmit_num, String is_focus, String uuid_flag, String video_length, String live_channel_id, String live_topic_id, String live_channel_tag, String summary) {
        this._id = _id;
        this.id = id;
        this.nid = nid;
        this.uid = uid;
        this.channel = channel;
        this.time = time;
        this.md5 = md5;
        this.cid = cid;
        this.album_pic = album_pic;
        this.title = title;
        this.zm = zm;
        this.url = url;
        this.comment = comment;
        this.pdate = pdate;
        this.source = source;
        this.module = module;
        this.share = share;
        this.news_from = news_from;
        this.open_type = open_type;
        this.news_type = news_type;
        this.news_data = news_data;
        this.news_stick = news_stick;
        this.news_stick_time = news_stick_time;
        this.transmit_num = transmit_num;
        this.is_focus = is_focus;
        this.uuid_flag = uuid_flag;
        this.video_length = video_length;
        this.live_channel_id = live_channel_id;
        this.live_topic_id = live_topic_id;
        this.live_channel_tag = live_channel_tag;
        this.summary = summary;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNid() {
        return nid;
    }

    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getChannel() {
        return channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getAlbum_pic() {
        return album_pic;
    }

    public void setAlbum_pic(String album_pic) {
        this.album_pic = album_pic;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getZm() {
        return zm;
    }

    public void setZm(String zm) {
        this.zm = zm;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getPdate() {
        return pdate;
    }

    public void setPdate(String pdate) {
        this.pdate = pdate;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }

    public String getShare() {
        return share;
    }

    public void setShare(String share) {
        this.share = share;
    }

    public String getNews_from() {
        return news_from;
    }

    public void setNews_from(String news_from) {
        this.news_from = news_from;
    }

    public String getOpen_type() {
        return open_type;
    }

    public void setOpen_type(String open_type) {
        this.open_type = open_type;
    }

    public String getNews_type() {
        return news_type;
    }

    public void setNews_type(String news_type) {
        this.news_type = news_type;
    }

    public String getNews_data() {
        return news_data;
    }

    public void setNews_data(String news_data) {
        this.news_data = news_data;
    }

    public String getNews_stick() {
        return news_stick;
    }

    public void setNews_stick(String news_stick) {
        this.news_stick = news_stick;
    }

    public String getNews_stick_time() {
        return news_stick_time;
    }

    public void setNews_stick_time(String news_stick_time) {
        this.news_stick_time = news_stick_time;
    }

    public String getTransmit_num() {
        return transmit_num;
    }

    public void setTransmit_num(String transmit_num) {
        this.transmit_num = transmit_num;
    }

    public String getIs_focus() {
        return is_focus;
    }

    public void setIs_focus(String is_focus) {
        this.is_focus = is_focus;
    }

    public String getUuid_flag() {
        return uuid_flag;
    }

    public void setUuid_flag(String uuid_flag) {
        this.uuid_flag = uuid_flag;
    }

    public String getVideo_length() {
        return video_length;
    }

    public void setVideo_length(String video_length) {
        this.video_length = video_length;
    }

    public String getLive_channel_id() {
        return live_channel_id;
    }

    public void setLive_channel_id(String live_channel_id) {
        this.live_channel_id = live_channel_id;
    }

    public String getLive_topic_id() {
        return live_topic_id;
    }

    public void setLive_topic_id(String live_topic_id) {
        this.live_topic_id = live_topic_id;
    }

    public String getLive_channel_tag() {
        return live_channel_tag;
    }

    public void setLive_channel_tag(String live_channel_tag) {
        this.live_channel_tag = live_channel_tag;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

}
