package com.jeremy.lychee.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WE_MEDIA_TOPIC.
 */
public class WeMediaTopic {

    private int id;
    private String title;
    private Integer weight;
    private String image;
    private String create_time;
    private String keyword;
    private String update_time;
    private Boolean is_sub;

    public WeMediaTopic() {
    }

    public WeMediaTopic(int id) {
        this.id = id;
    }

    public WeMediaTopic(int id, String title, Integer weight, String image, String create_time, String keyword, String update_time, Boolean is_sub) {
        this.id = id;
        this.title = title;
        this.weight = weight;
        this.image = image;
        this.create_time = create_time;
        this.keyword = keyword;
        this.update_time = update_time;
        this.is_sub = is_sub;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(String update_time) {
        this.update_time = update_time;
    }

    public Boolean getIs_sub() {
        return is_sub;
    }

    public void setIs_sub(Boolean is_sub) {
        this.is_sub = is_sub;
    }

}
